name: setting up environment

on: [push]

env:
  password: ${{ secrets.PASSWORD }}
  user: CytolyticTrashCan

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
             
    - name: run the bot
      continue-on-error: true
      timeout-minutes: 350
      run: |
             git config --global user.email "${{ secrets.EMAIL }}"
             git config --global user.name "$user" 
             sudo apt-get update && sudo apt-get upgrade
             sudo apt install expect -y
             git clone https://cytoo:$password@github.com/cytoo/grpscan.git bot;cd bot
             pip3 install -r requirements.txt
             python3 main.py"
             
    - name: loop
      continue-on-error: true
      timeout-minutes: 5
      run: | 
        mkdir bruh;cd bruh
         git add .
         git commit -m "bruh"
         expect -c "
         spawn git push -f 
         expect \"Username\"
         send \"CytolyticTrashCan\r\"
         expect \"Password\"
         send \"${{ secrets.PASSWORD }}\r\"
         expect \"master -> master\"
         set timeout -10
         interact
        git clone https://github.com/CytolyticTrashCan/runner nerd
        cd nerd
        echo "lool" >> k.txt
        git add .
        git commit -m "bruh"
        expect -c "
        spawn git push -f 
        expect \"Username\"
        send \"CytolyticTrashCan\r\"
        expect \"Password\"
        send \"${{ secrets.PASSWORD }}\r\"
        expect \"master -> master\"
        set timeout -10
        interact"
